from .getTotalRegistration import GetTotalRegistration
from .registerEvent import RegisterEvent
from .getAllRegistration import GetAllRegistration
from .isAlreadyRegistered import IsAlreadyRegistered
from .getEventRegistration import GetEventRegistration