from .getTotalRegistration import GetTotalRegistration
from .registerEvent import RegisterEvent
from .getAllRegistration import GetAllRegistration
from .isAlreadyRegistered import IsAlreadyRegistered
from .getEventRegistration import GetEventRegistration
from .getAllRegistrationCount import GetAllRegistrationCount
from .getBranchRegistrationCount import GetBranchRegistrationCount
from .getRegistrationPass import GetRegistrationPass