events = [
    {
        "branch_id": 1,
        "title": "Tech Innovators Meetup",
        "description": "An exciting event bringing together minds to explore new tech solutions.",
        "event_date": "2025-06-10T10:00:00",
        "location": "Block B, Nepal Telecom Complex, Tripureshwor Road, Kathmandu 44600, Nepal",
        "is_paid": True,
        "price": 322.25,
        "max_capacity": 125,
        "imageUrl": "event1.jpg"
    },
    {
        "branch_id": 1,
        "title": "Sustainable Future Summit",
        "description": "A summit on sustainability practices and innovation.",
        "event_date": "2025-06-12T10:00:00",
        "location": "Auditorium Hall, Pulchowk Engineering Campus, Pulchowk Rd, Lalitpur 44700, Nepal",
        "is_paid": True,
        "price": 211.35,
        "max_capacity": 244,
        "imageUrl": "event2.jpg"
    },
    {
        "branch_id": 1,
        "title": "Art & Expression Workshop",
        "description": "Express yourself through creative art in this collaborative workshop.",
        "event_date": "2025-06-14T10:00:00",
        "location": "Pokhara Art Gallery, Baidam Rd, Lakeside-6, Pokhara 33700, Nepal",
        "is_paid": True,
        "price": 356.05,
        "max_capacity": 286,
        "imageUrl": "event3.jpg"
    },
    {
        "branch_id": 1,
        "title": "Youth Leadership Conference",
        "description": "Motivational talks and team activities for emerging youth leaders.",
        "event_date": "2025-06-16T10:00:00",
        "location": "Biratnagar City Hall, Main Road, Opposite to Bhat-Bhateni, Biratnagar 56613, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 129,
        "imageUrl": "event4.jpg"
    },
    {
        "branch_id": 1,
        "title": "CodeSprint Hackathon",
        "description": "Join our intensive 48-hour hackathon to solve real-world problems.",
        "event_date": "2025-06-18T10:00:00",
        "location": "Fusemachines Nepal, 4th Floor, Trade Tower Nepal, Thapathali, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 53,
        "imageUrl": "event5.jpg"
    },
    {
        "branch_id": 1,
        "title": "Startup Pitch Fest",
        "description": "Pitch your ideas to real investors and get feedback.",
        "event_date": "2025-06-20T10:00:00",
        "location": "Nepal Communitere, 44600 Pipalbot, Patan, Lalitpur 44700, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 175,
        "imageUrl": "event6.jpg"
    },
    {
        "branch_id": 1,
        "title": "Photography Walk",
        "description": "Bring your camera and capture the beauty of Nepal.",
        "event_date": "2025-06-22T10:00:00",
        "location": "Meet at Basundhara Park Gate, Lakeside Rd, Pokhara 33700, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 130,
        "imageUrl": "event7.jpg"
    },
    {
        "branch_id": 1,
        "title": "Robotics Expo",
        "description": "Exhibit and interact with real robotic prototypes.",
        "event_date": "2025-06-24T10:00:00",
        "location": "Biratnagar Engineering College Auditorium, Tinpaini Road, Biratnagar 56613, Nepal",
        "is_paid": True,
        "price": 177.17,
        "max_capacity": 241,
        "imageUrl": "event8.jpg"
    },
    {
        "branch_id": 1,
        "title": "Mental Health Awareness Camp",
        "description": "Workshops and one-on-one sessions to boost mental health awareness.",
        "event_date": "2025-06-26T10:00:00",
        "location": "Tribhuvan University Teaching Hospital, Maharajgunj, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 68,
        "imageUrl": "event9.jpg"
    },
    {
        "branch_id": 1,
        "title": "Women in Tech Panel",
        "description": "Inspiring talks from women leaders shaping the tech world.",
        "event_date": "2025-06-28T10:00:00",
        "location": "British Council Nepal Auditorium, Lainchaur, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 245,
        "imageUrl": "event10.jpg"
    },
    {
        "branch_id": 1,
        "title": "AI & Ethics Symposium",
        "description": "Discuss the future of AI and its ethical implications.",
        "event_date": "2025-06-30T10:00:00",
        "location": "AI Research Center, IOE, Pulchowk, Lalitpur 44700, Nepal",
        "is_paid": True,
        "price": 921.14,
        "max_capacity": 130,
        "imageUrl": "event11.jpg"
    },
    {
        "branch_id": 1,
        "title": "Cultural Dance Night",
        "description": "Enjoy traditional dances and performances from all over Nepal.",
        "event_date": "2025-07-02T10:00:00",
        "location": "Gandaki Hall, Hotel Barahi, Lakeside, Pokhara 33700, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 186,
        "imageUrl": "event12.jpg"
    },
    {
        "branch_id": 1,
        "title": "Blockchain for Beginners",
        "description": "Get started with blockchain through this beginner-friendly session.",
        "event_date": "2025-07-04T10:00:00",
        "location": "Classroom C2, King's College, Babarmahal, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 123,
        "imageUrl": "event13.jpg"
    },
    {
        "branch_id": 1,
        "title": "Wildlife Conservation Talk",
        "description": "Support wildlife protection through this interactive talk.",
        "event_date": "2025-07-06T10:00:00",
        "location": "DNPWC HQ Meeting Room, Babarmahal, Kathmandu 44600, Nepal",
        "is_paid": True,
        "price": 538.33,
        "max_capacity": 186,
        "imageUrl": "event14.jpg"
    },
    {
        "branch_id": 1,
        "title": "Gaming Tournament: Pokhara Edition",
        "description": "Compete in the ultimate gaming challenge in Pokhara.",
        "event_date": "2025-07-08T10:00:00",
        "location": "LAN Arena, Opposite to Hallan Chowk, Pokhara 33700, Nepal",
        "is_paid": True,
        "price": 722.19,
        "max_capacity": 199,
        "imageUrl": "event15.jpg"
    },
    {
        "branch_id": 1,
        "title": "Film Screening & Discussion",
        "description": "Watch and analyze powerful indie films with directors.",
        "event_date": "2025-07-10T10:00:00",
        "location": "Film Development Board, Chabahil, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 242,
        "imageUrl": "event16.jpg"
    },
    {
        "branch_id": 1,
        "title": "AI in Healthcare Forum",
        "description": "Panel discussion on AI innovations in the health industry.",
        "event_date": "2025-07-12T10:00:00",
        "location": "Grande International Hospital, Tokha Road, Kathmandu 44600, Nepal",
        "is_paid": True,
        "price": 1.66,
        "max_capacity": 236,
        "imageUrl": "event17.jpg"
    },
    {
        "branch_id": 1,
        "title": "Mountain Cleanup Drive",
        "description": "Volunteer to clean up the Himalayas and promote eco-tourism.",
        "event_date": "2025-07-14T10:00:00",
        "location": "Thorang La Guest House, Manang, Nepal",
        "is_paid": True,
        "price": 865.77,
        "max_capacity": 198,
        "imageUrl": "event18.jpg"
    },
    {
        "branch_id": 1,
        "title": "Entrepreneurship 101",
        "description": "Learn how to start and scale your own business.",
        "event_date": "2025-07-16T10:00:00",
        "location": "Room 201, Kathmandu College of Management, Gwarko, Lalitpur 44700, Nepal",
        "is_paid": True,
        "price": 882.09,
        "max_capacity": 143,
        "imageUrl": "event19.jpg"
    },
    {
        "branch_id": 1,
        "title": "Virtual Reality Demo Day",
        "description": "Experience VR in education, games, and therapy.",
        "event_date": "2025-07-18T10:00:00",
        "location": "Lab 3, Nami College, Gokarneshwor, Kathmandu 44600, Nepal",
        "is_paid": True,
        "price": 810.57,
        "max_capacity": 63,
        "imageUrl": "event20.jpg"
    },
    {
        "branch_id": 1,
        "title": "Food & AgriTech Expo",
        "description": "Explore agriculture's future with tech innovations.",
        "event_date": "2025-07-20T10:00:00",
        "location": "Kisaan Tech Park, Bharatpur 44200, Nepal",
        "is_paid": True,
        "price": 600.13,
        "max_capacity": 80,
        "imageUrl": "event21.jpg"
    },
    {
        "branch_id": 1,
        "title": "Cybersecurity Bootcamp",
        "description": "Intensive course on securing apps and networks.",
        "event_date": "2025-07-22T10:00:00",
        "location": "Living with ICT, Sukedhara, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 66,
        "imageUrl": "event22.jpg"
    },
    {
        "branch_id": 1,
        "title": "Street Art Festival",
        "description": "Create murals and street art in this open-air fest.",
        "event_date": "2025-07-24T10:00:00",
        "location": "Basantapur Square, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 31,
        "imageUrl": "event23.jpg"
    },
    {
        "branch_id": 1,
        "title": "Public Speaking Masterclass",
        "description": "Sharpen your speaking skills with public feedback.",
        "event_date": "2025-07-26T10:00:00",
        "location": "ACE Institute of Management, New Baneshwor, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 131,
        "imageUrl": "event24.jpg"
    },
    {
        "branch_id": 1,
        "title": "IoT Devices Showcase",
        "description": "See real IoT gadgets in action.",
        "event_date": "2025-07-28T10:00:00",
        "location": "IoT Nepal Lab, Balkumari, Lalitpur 44700, Nepal",
        "is_paid": True,
        "price": 766.88,
        "max_capacity": 252,
        "imageUrl": "event25.jpg"
    },
    {
        "branch_id": 1,
        "title": "Online Freelancing Workshop",
        "description": "How to earn online with your existing skillsets.",
        "event_date": "2025-07-30T10:00:00",
        "location": "Women Lead Nepal, Kupondole, Lalitpur 44700, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 267,
        "imageUrl": "event26.jpg"
    },
    {
        "branch_id": 1,
        "title": "Green Coding Sprint",
        "description": "Create energy-efficient and optimized code.",
        "event_date": "2025-08-01T10:00:00",
        "location": "Leapfrog Technology, Gyaneshwor, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 282,
        "imageUrl": "event27.jpg"
    },
    {
        "branch_id": 1,
        "title": "App Development Training",
        "description": "Make your own app with guidance from developers.",
        "event_date": "2025-08-03T10:00:00",
        "location": "NCIT College, Balkumari, Lalitpur 44700, Nepal",
        "is_paid": True,
        "price": 277.23,
        "max_capacity": 193,
        "imageUrl": "event28.jpg"
    },
    {
        "branch_id": 1,
        "title": "Design Thinking Crash Course",
        "description": "Learn how to innovate under constraints.",
        "event_date": "2025-08-05T10:00:00",
        "location": "Nepal Innovation Lab, Jhamsikhel, Lalitpur 44700, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 63,
        "imageUrl": "event29.jpg"
    },
    {
        "branch_id": 1,
        "title": "Youth Career Counseling Fair",
        "description": "Explore career options and get guidance from pros.",
        "event_date": "2025-08-07T10:00:00",
        "location": "Rising Nepal Hostel Seminar Hall, Putalisadak, Kathmandu 44600, Nepal",
        "is_paid": False,
        "price": 0.0,
        "max_capacity": 177,
        "imageUrl": "event30.jpg"
    }
]