const data = [
    {
        "id": 1,
        "event_name": "Momo Cooking Workshop",
        "start_date": "2025-11-13",
        "end_date": "2025-11-13",
        "start_time": "10:00:00",
        "ticket_price": "NPR 101",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Join us for a hands-on workshop to learn the art of making authentic Nepali momo from scratch.",
        "image_file": "event001.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-10"
    },
    {
        "id": 2,
        "event_name": "Traditional Newa Dance Performance",
        "start_date": "2025-11-14",
        "end_date": "2025-11-14",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A mesmerizing performance showcasing the beauty and tradition of Newa dance.",
        "image_file": "event002.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-11"
    },
    {
        "id": 3,
        "event_name": "Hiking and Clean-Up Campaign",
        "start_date": "2025-11-15",
        "end_date": "2025-11-15",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Contribute to nature while enjoying a scenic hike\u2014organized for trail cleaning and awareness.",
        "image_file": "event003.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-12"
    },
    {
        "id": 4,
        "event_name": "AI and Startups in Nepal",
        "start_date": "2025-11-16",
        "end_date": "2025-11-16",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Explore how AI is shaping the future of startups in Nepal through expert talks and panels.",
        "image_file": "event004.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-13"
    },
    {
        "id": 5,
        "event_name": "Youth Empowerment Seminar",
        "start_date": "2025-11-17",
        "end_date": "2025-11-17",
        "start_time": "11:00:00",
        "ticket_price": "NPR 981",
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "An interactive session focusing on empowering Nepali youth through education and innovation.",
        "image_file": "event005.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-14"
    },
    {
        "id": 6,
        "event_name": "Art Exhibition on Nepali Heritage",
        "start_date": "2025-11-18",
        "end_date": "2025-11-18",
        "start_time": "12:00:00",
        "ticket_price": "NPR 180",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "A vibrant display of traditional and modern artworks inspired by Nepali culture and landscapes.",
        "image_file": "event006.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-15"
    },
    {
        "id": 7,
        "event_name": "Sustainable Agriculture Workshop",
        "start_date": "2025-11-19",
        "end_date": "2025-11-19",
        "start_time": "13:00:00",
        "ticket_price": "NPR 511",
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Learn sustainable and organic farming techniques being practiced in rural Nepal.",
        "image_file": "event007.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-16"
    },
    {
        "id": 8,
        "event_name": "Lok Sangeet Night",
        "start_date": "2025-11-20",
        "end_date": "2025-11-20",
        "start_time": "12:00:00",
        "ticket_price": "NPR 401",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Enjoy a night filled with soulful Nepali folk songs performed by local artists.",
        "image_file": "event008.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-17"
    },
    {
        "id": 9,
        "event_name": "Mountain Photography Exhibition",
        "start_date": "2025-11-21",
        "end_date": "2025-11-21",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Experience the majestic beauty of the Himalayas through the lens of talented photographers.",
        "image_file": "event009.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-18"
    },
    {
        "id": 10,
        "event_name": "Smart City Hackathon",
        "start_date": "2025-11-22",
        "end_date": "2025-11-22",
        "start_time": "11:00:00",
        "ticket_price": "NPR 141",
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "Compete and innovate for smarter Nepali cities at this overnight hackathon event.",
        "image_file": "event010.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-19"
    },
    {
        "id": 11,
        "event_name": "Indigenous Language Poetry Reading",
        "start_date": "2025-11-23",
        "end_date": "2025-11-23",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Celebrate the richness of Nepali languages through powerful poetry performances.",
        "image_file": "event011.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-20"
    },
    {
        "id": 12,
        "event_name": "Wildlife Conservation Awareness",
        "start_date": "2025-11-24",
        "end_date": "2025-11-24",
        "start_time": "11:00:00",
        "ticket_price": "NPR 314",
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A seminar focusing on preserving Nepal\u2019s wildlife and promoting eco-tourism.",
        "image_file": "event012.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-21"
    },
    {
        "id": 13,
        "event_name": "Tech Trends in Education",
        "start_date": "2025-11-25",
        "end_date": "2025-11-25",
        "start_time": "14:00:00",
        "ticket_price": "NPR 754",
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Dive into how technology is transforming learning environments across Nepal.",
        "image_file": "event013.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-22"
    },
    {
        "id": 14,
        "event_name": "Local Handicrafts Fair",
        "start_date": "2025-11-26",
        "end_date": "2025-11-26",
        "start_time": "13:00:00",
        "ticket_price": "NPR 627",
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Discover locally-made crafts and support artisans at this unique marketplace.",
        "image_file": "event014.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-23"
    },
    {
        "id": 15,
        "event_name": "Climate Action Meetup",
        "start_date": "2025-11-27",
        "end_date": "2025-11-27",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "Collaborate on solutions to combat climate change in the Nepalese context.",
        "image_file": "event015.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-24"
    },
    {
        "id": 16,
        "event_name": "Mental Health Talk for Teens",
        "start_date": "2025-11-28",
        "end_date": "2025-11-28",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "Open discussion and expert advice on teen mental health and well-being.",
        "image_file": "event016.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-25"
    },
    {
        "id": 17,
        "event_name": "Startup Pitch Event",
        "start_date": "2025-11-29",
        "end_date": "2025-11-29",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Entrepreneurs from across Nepal pitch their innovations to a panel of investors.",
        "image_file": "event017.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-26"
    },
    {
        "id": 18,
        "event_name": "Cultural Exchange Forum",
        "start_date": "2025-11-30",
        "end_date": "2025-11-30",
        "start_time": "09:00:00",
        "ticket_price": "NPR 454",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Meet people from different cultures and discuss shared values and experiences.",
        "image_file": "event018.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-27"
    },
    {
        "id": 19,
        "event_name": "Public Speaking Bootcamp",
        "start_date": "2025-12-01",
        "end_date": "2025-12-01",
        "start_time": "14:00:00",
        "ticket_price": "NPR 221",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Enhance your communication and leadership skills with this immersive workshop.",
        "image_file": "event019.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-28"
    },
    {
        "id": 20,
        "event_name": "Green Transport Solutions Meetup",
        "start_date": "2025-12-02",
        "end_date": "2025-12-02",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "A meetup to discuss electric vehicles, cycling infrastructure, and cleaner transport.",
        "image_file": "event020.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-29"
    },
    {
        "id": 21,
        "event_name": "Momo Cooking Workshop",
        "start_date": "2025-12-03",
        "end_date": "2025-12-03",
        "start_time": "09:00:00",
        "ticket_price": "NPR 349",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Join us for a hands-on workshop to learn the art of making authentic Nepali momo from scratch.",
        "image_file": "event021.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-30"
    },
    {
        "id": 22,
        "event_name": "Traditional Newa Dance Performance",
        "start_date": "2025-12-04",
        "end_date": "2025-12-04",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A mesmerizing performance showcasing the beauty and tradition of Newa dance.",
        "image_file": "event022.jpg",
        "club_id": 2,
        "registration_end_date": "2025-12-01"
    },
    {
        "id": 23,
        "event_name": "Hiking and Clean-Up Campaign",
        "start_date": "2025-12-05",
        "end_date": "2025-12-05",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Contribute to nature while enjoying a scenic hike\u2014organized for trail cleaning and awareness.",
        "image_file": "event023.jpg",
        "club_id": 3,
        "registration_end_date": "2025-12-02"
    },
    {
        "id": 24,
        "event_name": "AI and Startups in Nepal",
        "start_date": "2025-12-06",
        "end_date": "2025-12-06",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Explore how AI is shaping the future of startups in Nepal through expert talks and panels.",
        "image_file": "event024.jpg",
        "club_id": 4,
        "registration_end_date": "2025-12-03"
    },
    {
        "id": 25,
        "event_name": "Youth Empowerment Seminar",
        "start_date": "2025-12-07",
        "end_date": "2025-12-07",
        "start_time": "14:00:00",
        "ticket_price": "NPR 271",
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "An interactive session focusing on empowering Nepali youth through education and innovation.",
        "image_file": "event025.jpg",
        "club_id": 5,
        "registration_end_date": "2025-12-04"
    },
    {
        "id": 26,
        "event_name": "Art Exhibition on Nepali Heritage",
        "start_date": "2025-12-08",
        "end_date": "2025-12-08",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "A vibrant display of traditional and modern artworks inspired by Nepali culture and landscapes.",
        "image_file": "event026.jpg",
        "club_id": 6,
        "registration_end_date": "2025-12-05"
    },
    {
        "id": 27,
        "event_name": "Sustainable Agriculture Workshop",
        "start_date": "2025-12-09",
        "end_date": "2025-12-09",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Learn sustainable and organic farming techniques being practiced in rural Nepal.",
        "image_file": "event027.jpg",
        "club_id": 7,
        "registration_end_date": "2025-12-06"
    },
    {
        "id": 28,
        "event_name": "Lok Sangeet Night",
        "start_date": "2025-12-10",
        "end_date": "2025-12-10",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Enjoy a night filled with soulful Nepali folk songs performed by local artists.",
        "image_file": "event028.jpg",
        "club_id": 8,
        "registration_end_date": "2025-12-07"
    },
    {
        "id": 29,
        "event_name": "Mountain Photography Exhibition",
        "start_date": "2025-12-11",
        "end_date": "2025-12-11",
        "start_time": "12:00:00",
        "ticket_price": "NPR 778",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Experience the majestic beauty of the Himalayas through the lens of talented photographers.",
        "image_file": "event029.jpg",
        "club_id": 9,
        "registration_end_date": "2025-12-08"
    },
    {
        "id": 30,
        "event_name": "Smart City Hackathon",
        "start_date": "2025-12-12",
        "end_date": "2025-12-12",
        "start_time": "11:00:00",
        "ticket_price": "NPR 936",
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "Compete and innovate for smarter Nepali cities at this overnight hackathon event.",
        "image_file": "event030.jpg",
        "club_id": 10,
        "registration_end_date": "2025-12-09"
    },
    {
        "id": 31,
        "event_name": "Indigenous Language Poetry Reading",
        "start_date": "2025-11-13",
        "end_date": "2025-11-13",
        "start_time": "12:00:00",
        "ticket_price": "NPR 542",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Celebrate the richness of Nepali languages through powerful poetry performances.",
        "image_file": "event031.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-10"
    },
    {
        "id": 32,
        "event_name": "Wildlife Conservation Awareness",
        "start_date": "2025-11-14",
        "end_date": "2025-11-14",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A seminar focusing on preserving Nepal\u2019s wildlife and promoting eco-tourism.",
        "image_file": "event032.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-11"
    },
    {
        "id": 33,
        "event_name": "Tech Trends in Education",
        "start_date": "2025-11-15",
        "end_date": "2025-11-15",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Dive into how technology is transforming learning environments across Nepal.",
        "image_file": "event033.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-12"
    },
    {
        "id": 34,
        "event_name": "Local Handicrafts Fair",
        "start_date": "2025-11-16",
        "end_date": "2025-11-16",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Discover locally-made crafts and support artisans at this unique marketplace.",
        "image_file": "event034.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-13"
    },
    {
        "id": 35,
        "event_name": "Climate Action Meetup",
        "start_date": "2025-11-17",
        "end_date": "2025-11-17",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "Collaborate on solutions to combat climate change in the Nepalese context.",
        "image_file": "event035.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-14"
    },
    {
        "id": 36,
        "event_name": "Mental Health Talk for Teens",
        "start_date": "2025-11-18",
        "end_date": "2025-11-18",
        "start_time": "13:00:00",
        "ticket_price": "NPR 465",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "Open discussion and expert advice on teen mental health and well-being.",
        "image_file": "event036.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-15"
    },
    {
        "id": 37,
        "event_name": "Startup Pitch Event",
        "start_date": "2025-11-19",
        "end_date": "2025-11-19",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Entrepreneurs from across Nepal pitch their innovations to a panel of investors.",
        "image_file": "event037.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-16"
    },
    {
        "id": 38,
        "event_name": "Cultural Exchange Forum",
        "start_date": "2025-11-20",
        "end_date": "2025-11-20",
        "start_time": "10:00:00",
        "ticket_price": "NPR 674",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Meet people from different cultures and discuss shared values and experiences.",
        "image_file": "event038.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-17"
    },
    {
        "id": 39,
        "event_name": "Public Speaking Bootcamp",
        "start_date": "2025-11-21",
        "end_date": "2025-11-21",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Enhance your communication and leadership skills with this immersive workshop.",
        "image_file": "event039.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-18"
    },
    {
        "id": 40,
        "event_name": "Green Transport Solutions Meetup",
        "start_date": "2025-11-22",
        "end_date": "2025-11-22",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "A meetup to discuss electric vehicles, cycling infrastructure, and cleaner transport.",
        "image_file": "event040.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-19"
    },
    {
        "id": 41,
        "event_name": "Momo Cooking Workshop",
        "start_date": "2025-11-23",
        "end_date": "2025-11-23",
        "start_time": "14:00:00",
        "ticket_price": "NPR 838",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Join us for a hands-on workshop to learn the art of making authentic Nepali momo from scratch.",
        "image_file": "event041.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-20"
    },
    {
        "id": 42,
        "event_name": "Traditional Newa Dance Performance",
        "start_date": "2025-11-24",
        "end_date": "2025-11-24",
        "start_time": "09:00:00",
        "ticket_price": "NPR 126",
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A mesmerizing performance showcasing the beauty and tradition of Newa dance.",
        "image_file": "event042.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-21"
    },
    {
        "id": 43,
        "event_name": "Hiking and Clean-Up Campaign",
        "start_date": "2025-11-25",
        "end_date": "2025-11-25",
        "start_time": "10:00:00",
        "ticket_price": "NPR 730",
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Contribute to nature while enjoying a scenic hike\u2014organized for trail cleaning and awareness.",
        "image_file": "event043.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-22"
    },
    {
        "id": 44,
        "event_name": "AI and Startups in Nepal",
        "start_date": "2025-11-26",
        "end_date": "2025-11-26",
        "start_time": "10:00:00",
        "ticket_price": "NPR 921",
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Explore how AI is shaping the future of startups in Nepal through expert talks and panels.",
        "image_file": "event044.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-23"
    },
    {
        "id": 45,
        "event_name": "Youth Empowerment Seminar",
        "start_date": "2025-11-27",
        "end_date": "2025-11-27",
        "start_time": "11:00:00",
        "ticket_price": "NPR 799",
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "An interactive session focusing on empowering Nepali youth through education and innovation.",
        "image_file": "event045.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-24"
    },
    {
        "id": 46,
        "event_name": "Art Exhibition on Nepali Heritage",
        "start_date": "2025-11-28",
        "end_date": "2025-11-28",
        "start_time": "10:00:00",
        "ticket_price": "NPR 405",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "A vibrant display of traditional and modern artworks inspired by Nepali culture and landscapes.",
        "image_file": "event046.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-25"
    },
    {
        "id": 47,
        "event_name": "Sustainable Agriculture Workshop",
        "start_date": "2025-11-29",
        "end_date": "2025-11-29",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Learn sustainable and organic farming techniques being practiced in rural Nepal.",
        "image_file": "event047.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-26"
    },
    {
        "id": 48,
        "event_name": "Lok Sangeet Night",
        "start_date": "2025-11-30",
        "end_date": "2025-11-30",
        "start_time": "13:00:00",
        "ticket_price": "NPR 861",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Enjoy a night filled with soulful Nepali folk songs performed by local artists.",
        "image_file": "event048.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-27"
    },
    {
        "id": 49,
        "event_name": "Mountain Photography Exhibition",
        "start_date": "2025-12-01",
        "end_date": "2025-12-01",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Experience the majestic beauty of the Himalayas through the lens of talented photographers.",
        "image_file": "event049.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-28"
    },
    {
        "id": 50,
        "event_name": "Smart City Hackathon",
        "start_date": "2025-12-02",
        "end_date": "2025-12-02",
        "start_time": "12:00:00",
        "ticket_price": "NPR 285",
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "Compete and innovate for smarter Nepali cities at this overnight hackathon event.",
        "image_file": "event050.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-29"
    },
    {
        "id": 51,
        "event_name": "Indigenous Language Poetry Reading",
        "start_date": "2025-12-03",
        "end_date": "2025-12-03",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Celebrate the richness of Nepali languages through powerful poetry performances.",
        "image_file": "event051.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-30"
    },
    {
        "id": 52,
        "event_name": "Wildlife Conservation Awareness",
        "start_date": "2025-12-04",
        "end_date": "2025-12-04",
        "start_time": "14:00:00",
        "ticket_price": "NPR 563",
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A seminar focusing on preserving Nepal\u2019s wildlife and promoting eco-tourism.",
        "image_file": "event052.jpg",
        "club_id": 2,
        "registration_end_date": "2025-12-01"
    },
    {
        "id": 53,
        "event_name": "Tech Trends in Education",
        "start_date": "2025-12-05",
        "end_date": "2025-12-05",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Dive into how technology is transforming learning environments across Nepal.",
        "image_file": "event053.jpg",
        "club_id": 3,
        "registration_end_date": "2025-12-02"
    },
    {
        "id": 54,
        "event_name": "Local Handicrafts Fair",
        "start_date": "2025-12-06",
        "end_date": "2025-12-06",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Discover locally-made crafts and support artisans at this unique marketplace.",
        "image_file": "event054.jpg",
        "club_id": 4,
        "registration_end_date": "2025-12-03"
    },
    {
        "id": 55,
        "event_name": "Climate Action Meetup",
        "start_date": "2025-12-07",
        "end_date": "2025-12-07",
        "start_time": "13:00:00",
        "ticket_price": "NPR 302",
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "Collaborate on solutions to combat climate change in the Nepalese context.",
        "image_file": "event055.jpg",
        "club_id": 5,
        "registration_end_date": "2025-12-04"
    },
    {
        "id": 56,
        "event_name": "Mental Health Talk for Teens",
        "start_date": "2025-12-08",
        "end_date": "2025-12-08",
        "start_time": "14:00:00",
        "ticket_price": "NPR 407",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "Open discussion and expert advice on teen mental health and well-being.",
        "image_file": "event056.jpg",
        "club_id": 6,
        "registration_end_date": "2025-12-05"
    },
    {
        "id": 57,
        "event_name": "Startup Pitch Event",
        "start_date": "2025-12-09",
        "end_date": "2025-12-09",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Entrepreneurs from across Nepal pitch their innovations to a panel of investors.",
        "image_file": "event057.jpg",
        "club_id": 7,
        "registration_end_date": "2025-12-06"
    },
    {
        "id": 58,
        "event_name": "Cultural Exchange Forum",
        "start_date": "2025-12-10",
        "end_date": "2025-12-10",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Meet people from different cultures and discuss shared values and experiences.",
        "image_file": "event058.jpg",
        "club_id": 8,
        "registration_end_date": "2025-12-07"
    },
    {
        "id": 59,
        "event_name": "Public Speaking Bootcamp",
        "start_date": "2025-12-11",
        "end_date": "2025-12-11",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Enhance your communication and leadership skills with this immersive workshop.",
        "image_file": "event059.jpg",
        "club_id": 9,
        "registration_end_date": "2025-12-08"
    },
    {
        "id": 60,
        "event_name": "Green Transport Solutions Meetup",
        "start_date": "2025-12-12",
        "end_date": "2025-12-12",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "A meetup to discuss electric vehicles, cycling infrastructure, and cleaner transport.",
        "image_file": "event060.jpg",
        "club_id": 10,
        "registration_end_date": "2025-12-09"
    },
    {
        "id": 61,
        "event_name": "Momo Cooking Workshop",
        "start_date": "2025-11-13",
        "end_date": "2025-11-13",
        "start_time": "11:00:00",
        "ticket_price": "NPR 203",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Join us for a hands-on workshop to learn the art of making authentic Nepali momo from scratch.",
        "image_file": "event061.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-10"
    },
    {
        "id": 62,
        "event_name": "Traditional Newa Dance Performance",
        "start_date": "2025-11-14",
        "end_date": "2025-11-14",
        "start_time": "14:00:00",
        "ticket_price": "NPR 137",
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A mesmerizing performance showcasing the beauty and tradition of Newa dance.",
        "image_file": "event062.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-11"
    },
    {
        "id": 63,
        "event_name": "Hiking and Clean-Up Campaign",
        "start_date": "2025-11-15",
        "end_date": "2025-11-15",
        "start_time": "13:00:00",
        "ticket_price": "NPR 477",
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Contribute to nature while enjoying a scenic hike\u2014organized for trail cleaning and awareness.",
        "image_file": "event063.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-12"
    },
    {
        "id": 64,
        "event_name": "AI and Startups in Nepal",
        "start_date": "2025-11-16",
        "end_date": "2025-11-16",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Explore how AI is shaping the future of startups in Nepal through expert talks and panels.",
        "image_file": "event064.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-13"
    },
    {
        "id": 65,
        "event_name": "Youth Empowerment Seminar",
        "start_date": "2025-11-17",
        "end_date": "2025-11-17",
        "start_time": "12:00:00",
        "ticket_price": "NPR 226",
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "An interactive session focusing on empowering Nepali youth through education and innovation.",
        "image_file": "event065.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-14"
    },
    {
        "id": 66,
        "event_name": "Art Exhibition on Nepali Heritage",
        "start_date": "2025-11-18",
        "end_date": "2025-11-18",
        "start_time": "11:00:00",
        "ticket_price": "NPR 864",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "A vibrant display of traditional and modern artworks inspired by Nepali culture and landscapes.",
        "image_file": "event066.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-15"
    },
    {
        "id": 67,
        "event_name": "Sustainable Agriculture Workshop",
        "start_date": "2025-11-19",
        "end_date": "2025-11-19",
        "start_time": "12:00:00",
        "ticket_price": "NPR 203",
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Learn sustainable and organic farming techniques being practiced in rural Nepal.",
        "image_file": "event067.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-16"
    },
    {
        "id": 68,
        "event_name": "Lok Sangeet Night",
        "start_date": "2025-11-20",
        "end_date": "2025-11-20",
        "start_time": "13:00:00",
        "ticket_price": "NPR 433",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Enjoy a night filled with soulful Nepali folk songs performed by local artists.",
        "image_file": "event068.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-17"
    },
    {
        "id": 69,
        "event_name": "Mountain Photography Exhibition",
        "start_date": "2025-11-21",
        "end_date": "2025-11-21",
        "start_time": "13:00:00",
        "ticket_price": "NPR 721",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Experience the majestic beauty of the Himalayas through the lens of talented photographers.",
        "image_file": "event069.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-18"
    },
    {
        "id": 70,
        "event_name": "Smart City Hackathon",
        "start_date": "2025-11-22",
        "end_date": "2025-11-22",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "Compete and innovate for smarter Nepali cities at this overnight hackathon event.",
        "image_file": "event070.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-19"
    },
    {
        "id": 71,
        "event_name": "Indigenous Language Poetry Reading",
        "start_date": "2025-11-23",
        "end_date": "2025-11-23",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Celebrate the richness of Nepali languages through powerful poetry performances.",
        "image_file": "event071.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-20"
    },
    {
        "id": 72,
        "event_name": "Wildlife Conservation Awareness",
        "start_date": "2025-11-24",
        "end_date": "2025-11-24",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A seminar focusing on preserving Nepal\u2019s wildlife and promoting eco-tourism.",
        "image_file": "event072.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-21"
    },
    {
        "id": 73,
        "event_name": "Tech Trends in Education",
        "start_date": "2025-11-25",
        "end_date": "2025-11-25",
        "start_time": "10:00:00",
        "ticket_price": "NPR 133",
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Dive into how technology is transforming learning environments across Nepal.",
        "image_file": "event073.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-22"
    },
    {
        "id": 74,
        "event_name": "Local Handicrafts Fair",
        "start_date": "2025-11-26",
        "end_date": "2025-11-26",
        "start_time": "11:00:00",
        "ticket_price": "NPR 720",
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Discover locally-made crafts and support artisans at this unique marketplace.",
        "image_file": "event074.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-23"
    },
    {
        "id": 75,
        "event_name": "Climate Action Meetup",
        "start_date": "2025-11-27",
        "end_date": "2025-11-27",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "Collaborate on solutions to combat climate change in the Nepalese context.",
        "image_file": "event075.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-24"
    },
    {
        "id": 76,
        "event_name": "Mental Health Talk for Teens",
        "start_date": "2025-11-28",
        "end_date": "2025-11-28",
        "start_time": "10:00:00",
        "ticket_price": "NPR 224",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "Open discussion and expert advice on teen mental health and well-being.",
        "image_file": "event076.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-25"
    },
    {
        "id": 77,
        "event_name": "Startup Pitch Event",
        "start_date": "2025-11-29",
        "end_date": "2025-11-29",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Entrepreneurs from across Nepal pitch their innovations to a panel of investors.",
        "image_file": "event077.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-26"
    },
    {
        "id": 78,
        "event_name": "Cultural Exchange Forum",
        "start_date": "2025-11-30",
        "end_date": "2025-11-30",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Meet people from different cultures and discuss shared values and experiences.",
        "image_file": "event078.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-27"
    },
    {
        "id": 79,
        "event_name": "Public Speaking Bootcamp",
        "start_date": "2025-12-01",
        "end_date": "2025-12-01",
        "start_time": "13:00:00",
        "ticket_price": "NPR 136",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Enhance your communication and leadership skills with this immersive workshop.",
        "image_file": "event079.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-28"
    },
    {
        "id": 80,
        "event_name": "Green Transport Solutions Meetup",
        "start_date": "2025-12-02",
        "end_date": "2025-12-02",
        "start_time": "09:00:00",
        "ticket_price": "NPR 454",
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "A meetup to discuss electric vehicles, cycling infrastructure, and cleaner transport.",
        "image_file": "event080.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-29"
    },
    {
        "id": 81,
        "event_name": "Momo Cooking Workshop",
        "start_date": "2025-12-03",
        "end_date": "2025-12-03",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Join us for a hands-on workshop to learn the art of making authentic Nepali momo from scratch.",
        "image_file": "event081.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-30"
    },
    {
        "id": 82,
        "event_name": "Traditional Newa Dance Performance",
        "start_date": "2025-12-04",
        "end_date": "2025-12-04",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A mesmerizing performance showcasing the beauty and tradition of Newa dance.",
        "image_file": "event082.jpg",
        "club_id": 2,
        "registration_end_date": "2025-12-01"
    },
    {
        "id": 83,
        "event_name": "Hiking and Clean-Up Campaign",
        "start_date": "2025-12-05",
        "end_date": "2025-12-05",
        "start_time": "13:00:00",
        "ticket_price": "NPR 869",
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Contribute to nature while enjoying a scenic hike\u2014organized for trail cleaning and awareness.",
        "image_file": "event083.jpg",
        "club_id": 3,
        "registration_end_date": "2025-12-02"
    },
    {
        "id": 84,
        "event_name": "AI and Startups in Nepal",
        "start_date": "2025-12-06",
        "end_date": "2025-12-06",
        "start_time": "14:00:00",
        "ticket_price": "NPR 485",
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Explore how AI is shaping the future of startups in Nepal through expert talks and panels.",
        "image_file": "event084.jpg",
        "club_id": 4,
        "registration_end_date": "2025-12-03"
    },
    {
        "id": 85,
        "event_name": "Youth Empowerment Seminar",
        "start_date": "2025-12-07",
        "end_date": "2025-12-07",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "An interactive session focusing on empowering Nepali youth through education and innovation.",
        "image_file": "event085.jpg",
        "club_id": 5,
        "registration_end_date": "2025-12-04"
    },
    {
        "id": 86,
        "event_name": "Art Exhibition on Nepali Heritage",
        "start_date": "2025-12-08",
        "end_date": "2025-12-08",
        "start_time": "12:00:00",
        "ticket_price": "NPR 742",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "A vibrant display of traditional and modern artworks inspired by Nepali culture and landscapes.",
        "image_file": "event086.jpg",
        "club_id": 6,
        "registration_end_date": "2025-12-05"
    },
    {
        "id": 87,
        "event_name": "Sustainable Agriculture Workshop",
        "start_date": "2025-12-09",
        "end_date": "2025-12-09",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Learn sustainable and organic farming techniques being practiced in rural Nepal.",
        "image_file": "event087.jpg",
        "club_id": 7,
        "registration_end_date": "2025-12-06"
    },
    {
        "id": 88,
        "event_name": "Lok Sangeet Night",
        "start_date": "2025-12-10",
        "end_date": "2025-12-10",
        "start_time": "13:00:00",
        "ticket_price": "NPR 123",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Enjoy a night filled with soulful Nepali folk songs performed by local artists.",
        "image_file": "event088.jpg",
        "club_id": 8,
        "registration_end_date": "2025-12-07"
    },
    {
        "id": 89,
        "event_name": "Mountain Photography Exhibition",
        "start_date": "2025-12-11",
        "end_date": "2025-12-11",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Experience the majestic beauty of the Himalayas through the lens of talented photographers.",
        "image_file": "event089.jpg",
        "club_id": 9,
        "registration_end_date": "2025-12-08"
    },
    {
        "id": 90,
        "event_name": "Smart City Hackathon",
        "start_date": "2025-12-12",
        "end_date": "2025-12-12",
        "start_time": "14:00:00",
        "ticket_price": "NPR 188",
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "Compete and innovate for smarter Nepali cities at this overnight hackathon event.",
        "image_file": "event090.jpg",
        "club_id": 10,
        "registration_end_date": "2025-12-09"
    },
    {
        "id": 91,
        "event_name": "Indigenous Language Poetry Reading",
        "start_date": "2025-11-13",
        "end_date": "2025-11-13",
        "start_time": "14:00:00",
        "ticket_price": "NPR 167",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Celebrate the richness of Nepali languages through powerful poetry performances.",
        "image_file": "event091.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-10"
    },
    {
        "id": 92,
        "event_name": "Wildlife Conservation Awareness",
        "start_date": "2025-11-14",
        "end_date": "2025-11-14",
        "start_time": "13:00:00",
        "ticket_price": "NPR 328",
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A seminar focusing on preserving Nepal\u2019s wildlife and promoting eco-tourism.",
        "image_file": "event092.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-11"
    },
    {
        "id": 93,
        "event_name": "Tech Trends in Education",
        "start_date": "2025-11-15",
        "end_date": "2025-11-15",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Dive into how technology is transforming learning environments across Nepal.",
        "image_file": "event093.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-12"
    },
    {
        "id": 94,
        "event_name": "Local Handicrafts Fair",
        "start_date": "2025-11-16",
        "end_date": "2025-11-16",
        "start_time": "09:00:00",
        "ticket_price": "NPR 871",
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Discover locally-made crafts and support artisans at this unique marketplace.",
        "image_file": "event094.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-13"
    },
    {
        "id": 95,
        "event_name": "Climate Action Meetup",
        "start_date": "2025-11-17",
        "end_date": "2025-11-17",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "Collaborate on solutions to combat climate change in the Nepalese context.",
        "image_file": "event095.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-14"
    },
    {
        "id": 96,
        "event_name": "Mental Health Talk for Teens",
        "start_date": "2025-11-18",
        "end_date": "2025-11-18",
        "start_time": "09:00:00",
        "ticket_price": "NPR 184",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "Open discussion and expert advice on teen mental health and well-being.",
        "image_file": "event096.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-15"
    },
    {
        "id": 97,
        "event_name": "Startup Pitch Event",
        "start_date": "2025-11-19",
        "end_date": "2025-11-19",
        "start_time": "10:00:00",
        "ticket_price": "NPR 540",
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Entrepreneurs from across Nepal pitch their innovations to a panel of investors.",
        "image_file": "event097.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-16"
    },
    {
        "id": 98,
        "event_name": "Cultural Exchange Forum",
        "start_date": "2025-11-20",
        "end_date": "2025-11-20",
        "start_time": "12:00:00",
        "ticket_price": "NPR 710",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Meet people from different cultures and discuss shared values and experiences.",
        "image_file": "event098.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-17"
    },
    {
        "id": 99,
        "event_name": "Public Speaking Bootcamp",
        "start_date": "2025-11-21",
        "end_date": "2025-11-21",
        "start_time": "10:00:00",
        "ticket_price": "NPR 240",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Enhance your communication and leadership skills with this immersive workshop.",
        "image_file": "event099.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-18"
    },
    {
        "id": 100,
        "event_name": "Green Transport Solutions Meetup",
        "start_date": "2025-11-22",
        "end_date": "2025-11-22",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "A meetup to discuss electric vehicles, cycling infrastructure, and cleaner transport.",
        "image_file": "event100.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-19"
    },
    {
        "id": 101,
        "event_name": "Momo Cooking Workshop",
        "start_date": "2025-11-23",
        "end_date": "2025-11-23",
        "start_time": "12:00:00",
        "ticket_price": "NPR 353",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Join us for a hands-on workshop to learn the art of making authentic Nepali momo from scratch.",
        "image_file": "event101.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-20"
    },
    {
        "id": 102,
        "event_name": "Traditional Newa Dance Performance",
        "start_date": "2025-11-24",
        "end_date": "2025-11-24",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A mesmerizing performance showcasing the beauty and tradition of Newa dance.",
        "image_file": "event102.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-21"
    },
    {
        "id": 103,
        "event_name": "Hiking and Clean-Up Campaign",
        "start_date": "2025-11-25",
        "end_date": "2025-11-25",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Contribute to nature while enjoying a scenic hike\u2014organized for trail cleaning and awareness.",
        "image_file": "event103.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-22"
    },
    {
        "id": 104,
        "event_name": "AI and Startups in Nepal",
        "start_date": "2025-11-26",
        "end_date": "2025-11-26",
        "start_time": "14:00:00",
        "ticket_price": "NPR 707",
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Explore how AI is shaping the future of startups in Nepal through expert talks and panels.",
        "image_file": "event104.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-23"
    },
    {
        "id": 105,
        "event_name": "Youth Empowerment Seminar",
        "start_date": "2025-11-27",
        "end_date": "2025-11-27",
        "start_time": "13:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "An interactive session focusing on empowering Nepali youth through education and innovation.",
        "image_file": "event105.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-24"
    },
    {
        "id": 106,
        "event_name": "Art Exhibition on Nepali Heritage",
        "start_date": "2025-11-28",
        "end_date": "2025-11-28",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "A vibrant display of traditional and modern artworks inspired by Nepali culture and landscapes.",
        "image_file": "event106.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-25"
    },
    {
        "id": 107,
        "event_name": "Sustainable Agriculture Workshop",
        "start_date": "2025-11-29",
        "end_date": "2025-11-29",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Learn sustainable and organic farming techniques being practiced in rural Nepal.",
        "image_file": "event107.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-26"
    },
    {
        "id": 108,
        "event_name": "Lok Sangeet Night",
        "start_date": "2025-11-30",
        "end_date": "2025-11-30",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Enjoy a night filled with soulful Nepali folk songs performed by local artists.",
        "image_file": "event108.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-27"
    },
    {
        "id": 109,
        "event_name": "Mountain Photography Exhibition",
        "start_date": "2025-12-01",
        "end_date": "2025-12-01",
        "start_time": "09:00:00",
        "ticket_price": "NPR 607",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Experience the majestic beauty of the Himalayas through the lens of talented photographers.",
        "image_file": "event109.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-28"
    },
    {
        "id": 110,
        "event_name": "Smart City Hackathon",
        "start_date": "2025-12-02",
        "end_date": "2025-12-02",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "Compete and innovate for smarter Nepali cities at this overnight hackathon event.",
        "image_file": "event110.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-29"
    },
    {
        "id": 111,
        "event_name": "Indigenous Language Poetry Reading",
        "start_date": "2025-12-03",
        "end_date": "2025-12-03",
        "start_time": "11:00:00",
        "ticket_price": "NPR 915",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Celebrate the richness of Nepali languages through powerful poetry performances.",
        "image_file": "event111.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-30"
    },
    {
        "id": 112,
        "event_name": "Wildlife Conservation Awareness",
        "start_date": "2025-12-04",
        "end_date": "2025-12-04",
        "start_time": "13:00:00",
        "ticket_price": "NPR 332",
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A seminar focusing on preserving Nepal\u2019s wildlife and promoting eco-tourism.",
        "image_file": "event112.jpg",
        "club_id": 2,
        "registration_end_date": "2025-12-01"
    },
    {
        "id": 113,
        "event_name": "Tech Trends in Education",
        "start_date": "2025-12-05",
        "end_date": "2025-12-05",
        "start_time": "09:00:00",
        "ticket_price": "NPR 700",
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Dive into how technology is transforming learning environments across Nepal.",
        "image_file": "event113.jpg",
        "club_id": 3,
        "registration_end_date": "2025-12-02"
    },
    {
        "id": 114,
        "event_name": "Local Handicrafts Fair",
        "start_date": "2025-12-06",
        "end_date": "2025-12-06",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Discover locally-made crafts and support artisans at this unique marketplace.",
        "image_file": "event114.jpg",
        "club_id": 4,
        "registration_end_date": "2025-12-03"
    },
    {
        "id": 115,
        "event_name": "Climate Action Meetup",
        "start_date": "2025-12-07",
        "end_date": "2025-12-07",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "Collaborate on solutions to combat climate change in the Nepalese context.",
        "image_file": "event115.jpg",
        "club_id": 5,
        "registration_end_date": "2025-12-04"
    },
    {
        "id": 116,
        "event_name": "Mental Health Talk for Teens",
        "start_date": "2025-12-08",
        "end_date": "2025-12-08",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "Open discussion and expert advice on teen mental health and well-being.",
        "image_file": "event116.jpg",
        "club_id": 6,
        "registration_end_date": "2025-12-05"
    },
    {
        "id": 117,
        "event_name": "Startup Pitch Event",
        "start_date": "2025-12-09",
        "end_date": "2025-12-09",
        "start_time": "12:00:00",
        "ticket_price": "NPR 826",
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Entrepreneurs from across Nepal pitch their innovations to a panel of investors.",
        "image_file": "event117.jpg",
        "club_id": 7,
        "registration_end_date": "2025-12-06"
    },
    {
        "id": 118,
        "event_name": "Cultural Exchange Forum",
        "start_date": "2025-12-10",
        "end_date": "2025-12-10",
        "start_time": "11:00:00",
        "ticket_price": "NPR 375",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Meet people from different cultures and discuss shared values and experiences.",
        "image_file": "event118.jpg",
        "club_id": 8,
        "registration_end_date": "2025-12-07"
    },
    {
        "id": 119,
        "event_name": "Public Speaking Bootcamp",
        "start_date": "2025-12-11",
        "end_date": "2025-12-11",
        "start_time": "11:00:00",
        "ticket_price": "NPR 403",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Enhance your communication and leadership skills with this immersive workshop.",
        "image_file": "event119.jpg",
        "club_id": 9,
        "registration_end_date": "2025-12-08"
    },
    {
        "id": 120,
        "event_name": "Green Transport Solutions Meetup",
        "start_date": "2025-12-12",
        "end_date": "2025-12-12",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "A meetup to discuss electric vehicles, cycling infrastructure, and cleaner transport.",
        "image_file": "event120.jpg",
        "club_id": 10,
        "registration_end_date": "2025-12-09"
    },
    {
        "id": 121,
        "event_name": "Momo Cooking Workshop",
        "start_date": "2025-11-13",
        "end_date": "2025-11-13",
        "start_time": "13:00:00",
        "ticket_price": "NPR 555",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Join us for a hands-on workshop to learn the art of making authentic Nepali momo from scratch.",
        "image_file": "event121.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-10"
    },
    {
        "id": 122,
        "event_name": "Traditional Newa Dance Performance",
        "start_date": "2025-11-14",
        "end_date": "2025-11-14",
        "start_time": "11:00:00",
        "ticket_price": "NPR 186",
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A mesmerizing performance showcasing the beauty and tradition of Newa dance.",
        "image_file": "event122.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-11"
    },
    {
        "id": 123,
        "event_name": "Hiking and Clean-Up Campaign",
        "start_date": "2025-11-15",
        "end_date": "2025-11-15",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Contribute to nature while enjoying a scenic hike\u2014organized for trail cleaning and awareness.",
        "image_file": "event123.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-12"
    },
    {
        "id": 124,
        "event_name": "AI and Startups in Nepal",
        "start_date": "2025-11-16",
        "end_date": "2025-11-16",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Explore how AI is shaping the future of startups in Nepal through expert talks and panels.",
        "image_file": "event124.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-13"
    },
    {
        "id": 125,
        "event_name": "Youth Empowerment Seminar",
        "start_date": "2025-11-17",
        "end_date": "2025-11-17",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "An interactive session focusing on empowering Nepali youth through education and innovation.",
        "image_file": "event125.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-14"
    },
    {
        "id": 126,
        "event_name": "Art Exhibition on Nepali Heritage",
        "start_date": "2025-11-18",
        "end_date": "2025-11-18",
        "start_time": "09:00:00",
        "ticket_price": "NPR 699",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "A vibrant display of traditional and modern artworks inspired by Nepali culture and landscapes.",
        "image_file": "event126.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-15"
    },
    {
        "id": 127,
        "event_name": "Sustainable Agriculture Workshop",
        "start_date": "2025-11-19",
        "end_date": "2025-11-19",
        "start_time": "12:00:00",
        "ticket_price": "NPR 220",
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Learn sustainable and organic farming techniques being practiced in rural Nepal.",
        "image_file": "event127.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-16"
    },
    {
        "id": 128,
        "event_name": "Lok Sangeet Night",
        "start_date": "2025-11-20",
        "end_date": "2025-11-20",
        "start_time": "10:00:00",
        "ticket_price": "NPR 704",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Enjoy a night filled with soulful Nepali folk songs performed by local artists.",
        "image_file": "event128.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-17"
    },
    {
        "id": 129,
        "event_name": "Mountain Photography Exhibition",
        "start_date": "2025-11-21",
        "end_date": "2025-11-21",
        "start_time": "11:00:00",
        "ticket_price": "NPR 579",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Experience the majestic beauty of the Himalayas through the lens of talented photographers.",
        "image_file": "event129.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-18"
    },
    {
        "id": 130,
        "event_name": "Smart City Hackathon",
        "start_date": "2025-11-22",
        "end_date": "2025-11-22",
        "start_time": "09:00:00",
        "ticket_price": "NPR 237",
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "Compete and innovate for smarter Nepali cities at this overnight hackathon event.",
        "image_file": "event130.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-19"
    },
    {
        "id": 131,
        "event_name": "Indigenous Language Poetry Reading",
        "start_date": "2025-11-23",
        "end_date": "2025-11-23",
        "start_time": "09:00:00",
        "ticket_price": null,
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Celebrate the richness of Nepali languages through powerful poetry performances.",
        "image_file": "event131.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-20"
    },
    {
        "id": 132,
        "event_name": "Wildlife Conservation Awareness",
        "start_date": "2025-11-24",
        "end_date": "2025-11-24",
        "start_time": "10:00:00",
        "ticket_price": null,
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A seminar focusing on preserving Nepal\u2019s wildlife and promoting eco-tourism.",
        "image_file": "event132.jpg",
        "club_id": 2,
        "registration_end_date": "2025-11-21"
    },
    {
        "id": 133,
        "event_name": "Tech Trends in Education",
        "start_date": "2025-11-25",
        "end_date": "2025-11-25",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Dive into how technology is transforming learning environments across Nepal.",
        "image_file": "event133.jpg",
        "club_id": 3,
        "registration_end_date": "2025-11-22"
    },
    {
        "id": 134,
        "event_name": "Local Handicrafts Fair",
        "start_date": "2025-11-26",
        "end_date": "2025-11-26",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Discover locally-made crafts and support artisans at this unique marketplace.",
        "image_file": "event134.jpg",
        "club_id": 4,
        "registration_end_date": "2025-11-23"
    },
    {
        "id": 135,
        "event_name": "Climate Action Meetup",
        "start_date": "2025-11-27",
        "end_date": "2025-11-27",
        "start_time": "12:00:00",
        "ticket_price": "NPR 415",
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "Collaborate on solutions to combat climate change in the Nepalese context.",
        "image_file": "event135.jpg",
        "club_id": 5,
        "registration_end_date": "2025-11-24"
    },
    {
        "id": 136,
        "event_name": "Mental Health Talk for Teens",
        "start_date": "2025-11-28",
        "end_date": "2025-11-28",
        "start_time": "14:00:00",
        "ticket_price": "NPR 446",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "Open discussion and expert advice on teen mental health and well-being.",
        "image_file": "event136.jpg",
        "club_id": 6,
        "registration_end_date": "2025-11-25"
    },
    {
        "id": 137,
        "event_name": "Startup Pitch Event",
        "start_date": "2025-11-29",
        "end_date": "2025-11-29",
        "start_time": "11:00:00",
        "ticket_price": "NPR 956",
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Entrepreneurs from across Nepal pitch their innovations to a panel of investors.",
        "image_file": "event137.jpg",
        "club_id": 7,
        "registration_end_date": "2025-11-26"
    },
    {
        "id": 138,
        "event_name": "Cultural Exchange Forum",
        "start_date": "2025-11-30",
        "end_date": "2025-11-30",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Meet people from different cultures and discuss shared values and experiences.",
        "image_file": "event138.jpg",
        "club_id": 8,
        "registration_end_date": "2025-11-27"
    },
    {
        "id": 139,
        "event_name": "Public Speaking Bootcamp",
        "start_date": "2025-12-01",
        "end_date": "2025-12-01",
        "start_time": "13:00:00",
        "ticket_price": "NPR 886",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Enhance your communication and leadership skills with this immersive workshop.",
        "image_file": "event139.jpg",
        "club_id": 9,
        "registration_end_date": "2025-11-28"
    },
    {
        "id": 140,
        "event_name": "Green Transport Solutions Meetup",
        "start_date": "2025-12-02",
        "end_date": "2025-12-02",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "A meetup to discuss electric vehicles, cycling infrastructure, and cleaner transport.",
        "image_file": "event140.jpg",
        "club_id": 10,
        "registration_end_date": "2025-11-29"
    },
    {
        "id": 141,
        "event_name": "Momo Cooking Workshop",
        "start_date": "2025-12-03",
        "end_date": "2025-12-03",
        "start_time": "09:00:00",
        "ticket_price": "NPR 685",
        "location": "Nepal Academy Hall, Kamaladi, Kathmandu 44600",
        "description": "Join us for a hands-on workshop to learn the art of making authentic Nepali momo from scratch.",
        "image_file": "event141.jpg",
        "club_id": 1,
        "registration_end_date": "2025-11-30"
    },
    {
        "id": 142,
        "event_name": "Traditional Newa Dance Performance",
        "start_date": "2025-12-04",
        "end_date": "2025-12-04",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Yala Maya Kendra, Patan Dhoka, Lalitpur 44700",
        "description": "A mesmerizing performance showcasing the beauty and tradition of Newa dance.",
        "image_file": "event142.jpg",
        "club_id": 2,
        "registration_end_date": "2025-12-01"
    },
    {
        "id": 143,
        "event_name": "Hiking and Clean-Up Campaign",
        "start_date": "2025-12-05",
        "end_date": "2025-12-05",
        "start_time": "14:00:00",
        "ticket_price": null,
        "location": "Bhaktapur Durbar Square Museum Hall, Bhaktapur 44800",
        "description": "Contribute to nature while enjoying a scenic hike\u2014organized for trail cleaning and awareness.",
        "image_file": "event143.jpg",
        "club_id": 3,
        "registration_end_date": "2025-12-02"
    },
    {
        "id": 144,
        "event_name": "AI and Startups in Nepal",
        "start_date": "2025-12-06",
        "end_date": "2025-12-06",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Pokhara International Mountain Museum, Rato Pairo, Pokhara 33700",
        "description": "Explore how AI is shaping the future of startups in Nepal through expert talks and panels.",
        "image_file": "event144.jpg",
        "club_id": 4,
        "registration_end_date": "2025-12-03"
    },
    {
        "id": 145,
        "event_name": "Youth Empowerment Seminar",
        "start_date": "2025-12-07",
        "end_date": "2025-12-07",
        "start_time": "12:00:00",
        "ticket_price": null,
        "location": "Tharu Cultural Museum & Research Center, Bachhauli, Sauraha 44200",
        "description": "An interactive session focusing on empowering Nepali youth through education and innovation.",
        "image_file": "event145.jpg",
        "club_id": 5,
        "registration_end_date": "2025-12-04"
    },
    {
        "id": 146,
        "event_name": "Art Exhibition on Nepali Heritage",
        "start_date": "2025-12-08",
        "end_date": "2025-12-08",
        "start_time": "11:00:00",
        "ticket_price": "NPR 558",
        "location": "Aashirwad Banquet, Airport Road, Biratnagar 56613",
        "description": "A vibrant display of traditional and modern artworks inspired by Nepali culture and landscapes.",
        "image_file": "event146.jpg",
        "club_id": 6,
        "registration_end_date": "2025-12-05"
    },
    {
        "id": 147,
        "event_name": "Sustainable Agriculture Workshop",
        "start_date": "2025-12-09",
        "end_date": "2025-12-09",
        "start_time": "11:00:00",
        "ticket_price": null,
        "location": "Auditorium Hall, BP Koirala Institute of Health Sciences, Dharan 56700",
        "description": "Learn sustainable and organic farming techniques being practiced in rural Nepal.",
        "image_file": "event147.jpg",
        "club_id": 7,
        "registration_end_date": "2025-12-06"
    },
    {
        "id": 148,
        "event_name": "Lok Sangeet Night",
        "start_date": "2025-12-10",
        "end_date": "2025-12-10",
        "start_time": "13:00:00",
        "ticket_price": "NPR 410",
        "location": "Lumbini Banquet, Devinagar, Butwal 32907",
        "description": "Enjoy a night filled with soulful Nepali folk songs performed by local artists.",
        "image_file": "event148.jpg",
        "club_id": 8,
        "registration_end_date": "2025-12-07"
    },
    {
        "id": 149,
        "event_name": "Mountain Photography Exhibition",
        "start_date": "2025-12-11",
        "end_date": "2025-12-11",
        "start_time": "12:00:00",
        "ticket_price": "NPR 841",
        "location": "Hotel Siddhartha Conference Hall, Surkhet Road, Nepalgunj 21900",
        "description": "Experience the majestic beauty of the Himalayas through the lens of talented photographers.",
        "image_file": "event149.jpg",
        "club_id": 9,
        "registration_end_date": "2025-12-08"
    },
    {
        "id": 150,
        "event_name": "Smart City Hackathon",
        "start_date": "2025-12-12",
        "end_date": "2025-12-12",
        "start_time": "12:00:00",
        "ticket_price": "NPR 578",
        "location": "Mithila Yatri Bhawan, Janaki Mandir Road, Janakpur 45600",
        "description": "Compete and innovate for smarter Nepali cities at this overnight hackathon event.",
        "image_file": "event150.jpg",
        "club_id": 10,
        "registration_end_date": "2025-12-09"
    }
];

export default data;